{
  "studentId": "fe88383d-b8d5-4acf-9217-578cfed0e3a7",
  "studentName": "Denize Batista Meira",
  "aiValidation": {
    "studentId": "fe88383d-b8d5-4acf-9217-578cfed0e3a7",
    "weekStart": "2026-07-13",
    "weekEnd": "2026-07-19",
    "expectedWorkoutCount": 2,
    "expectedWorkoutDates": [
      "2026-07-13",
      "2026-07-15"
    ],
    "validationKey": "FVD|fe88383d-b8d5-4acf-9217-578cfed0e3a7|2026-07-13|2|2026-07-13_2026-07-15"
  },
  "evolutionDecision": {
    "status": "PRE_PLANEJAMENTO_CONSERVADOR",
    "reason": "Primeira semana da experiência, sem histórico de execução no sistema. A proposta prioriza base, técnica, estabilidade, mobilidade e fortalecimento útil para prevenção de lesões na corrida, sem progressão agressiva.",
    "requiresReviewBeforeRelease": true,
    "reviewAlerts": [
      "Confirmar com a aluna se permanece sem dor ou desconforto antes de liberar os treinos.",
      "Revisar cargas e amplitudes presencialmente antes da execução.",
      "Confirmar a altura cadastrada, pois o valor informado de 80 cm parece inconsistente.",
      "Revisar o treino antes da liberação por ser a primeira semana sem dados de adesão."
    ]
  },
  "workouts": [
    {
      "name": "Treino A - Base de força e estabilidade para corrida",
      "date": "2026-07-13",
      "description": "Sessão de adaptação com foco em mobilidade de tornozelo e quadril, ativação de glúteos, força de pernas e estabilidade de core.",
      "objective": "Construir uma base segura para a corrida, melhorando controle de joelhos, quadris, tornozelos e tronco.",
      "focusAreas": "Pernas, glúteos, core, equilíbrio e mobilidade de tornozelo e quadril",
      "intensity": "moderada",
      "estimatedDurationMinutes": 48,
      "estimatedCaloriesMin": 180,
      "estimatedCaloriesMax": 260,
      "studentSummary": "Este treino prepara seu corpo para correr com mais estabilidade. O foco é fortalecer pernas, glúteos e core, além de melhorar a mobilidade necessária para uma passada mais controlada.",
      "safetyNote": "O gasto calórico é apenas uma estimativa. Execute com técnica, sem pressa, e interrompa ou adapte qualquer exercício que provoque dor fora do esforço esperado.",
      "notes": "Primeira sessão da experiência. Professor deve confirmar ausência de dor, ajustar cargas e observar alinhamento dos joelhos e controle do tronco.",
      "exercises": [
        {
          "exerciseId": "3fc6245f-22e9-459a-a726-201379632ce8",
          "name": "Marcha estacionária",
          "description": "Marcha no lugar para aquecimento e condicionamento leve.",
          "purpose": "Elevar gradualmente a temperatura corporal e preparar articulações para a sessão.",
          "instructions": "Marchar no lugar elevando os joelhos em amplitude confortável e mantendo postura alta.",
          "safetyGuidance": "Manter ritmo conversável, sem impacto forte, tontura ou falta de ar importante.",
          "series": 1,
          "reps": "5 minutos",
          "weight": "sem carga",
          "restTime": "30s",
          "notes": "Usar como aquecimento progressivo.",
          "order": 0
        },
        {
          "exerciseId": "6cbbaf41-4a9d-40ed-a7f6-fcae9010346c",
          "name": "Mobilidade de tornozelo na parede",
          "description": "Mobilidade de tornozelo para agachamento e corrida.",
          "purpose": "Melhorar a mobilidade do tornozelo e favorecer uma passada e um agachamento mais controlados.",
          "instructions": "Levar o joelho em direção à parede mantendo o calcanhar no chão.",
          "safetyGuidance": "Movimento suave e progressivo, sem retirar o calcanhar ou forçar dor.",
          "series": 2,
          "reps": "10 por lado",
          "weight": "sem carga",
          "restTime": "30s",
          "notes": "Controlar o alinhamento do joelho.",
          "order": 1
        },
        {
          "exerciseId": "725a8891-24b0-442a-b0b7-794381320e89",
          "name": "Clam shell",
          "description": "Ativação de glúteo médio com joelhos flexionados.",
          "purpose": "Ativar o glúteo médio para ajudar na estabilidade do quadril e do joelho durante a corrida.",
          "instructions": "De lado, abrir o joelho de cima mantendo os pés juntos e o quadril estável.",
          "safetyGuidance": "Não rodar o tronco para trás e usar amplitude controlada.",
          "series": 2,
          "reps": "12 por lado",
          "weight": "elástico leve opcional",
          "restTime": "40s",
          "notes": "Priorizar ativação e controle, não amplitude máxima.",
          "order": 2
        },
        {
          "exerciseId": "d92421e0-76d4-4fbf-9820-874018ee8505",
          "name": "Agachamento goblet",
          "description": "Agachamento com carga junto ao peito para pernas e glúteos.",
          "purpose": "Fortalecer pernas e glúteos com controle de tronco e joelhos.",
          "instructions": "Segurar a carga junto ao peito, descer com controle e subir mantendo o tronco firme.",
          "safetyGuidance": "Usar carga leve na adaptação, manter calcanhares apoiados e interromper se houver dor no joelho, quadril ou lombar.",
          "series": 3,
          "reps": "10",
          "weight": "carga leve a moderada, definida pelo professor",
          "restTime": "75s",
          "notes": "Observar joelhos alinhados e carga próxima ao corpo.",
          "order": 3
        },
        {
          "exerciseId": "24cfb60b-233d-47ba-9abd-9dc141acd4ee",
          "name": "Avanço estático",
          "description": "Avanço com os pés fixos para força e equilíbrio.",
          "purpose": "Fortalecer de forma unilateral e melhorar estabilidade útil para a corrida.",
          "instructions": "Com um pé à frente e outro atrás, descer e subir mantendo controle e alinhamento.",
          "safetyGuidance": "Usar apoio lateral se necessário e reduzir amplitude se houver desconforto.",
          "series": 3,
          "reps": "8 por lado",
          "weight": "sem carga ou carga leve",
          "restTime": "60s",
          "notes": "Priorizar estabilidade antes de aumentar carga.",
          "order": 4
        },
        {
          "exerciseId": "59ca9d16-fb20-4f90-9fb5-7a77c050b465",
          "name": "Elevação de panturrilha em pé",
          "description": "Fortalecimento de panturrilhas para corrida e estabilidade.",
          "purpose": "Fortalecer panturrilhas e melhorar suporte para a passada.",
          "instructions": "Subir na ponta dos pés e descer de forma controlada.",
          "safetyGuidance": "Evitar amplitude dolorosa e usar apoio estável se necessário.",
          "series": 3,
          "reps": "12-15",
          "weight": "peso corporal",
          "restTime": "45s",
          "notes": "Descer lentamente e evitar jogar o corpo para frente.",
          "order": 5
        },
        {
          "exerciseId": "4b45bb3d-3b28-42b9-a5ae-97f9c42f4a19",
          "name": "Bird dog",
          "description": "Estabilidade de core e quadril em quatro apoios.",
          "purpose": "Melhorar o controle do tronco e do quadril durante movimentos alternados.",
          "instructions": "Em quatro apoios, estender braço e perna opostos sem girar o tronco.",
          "safetyGuidance": "Executar devagar, com amplitude confortável e sem arquear a lombar.",
          "series": 3,
          "reps": "8 por lado",
          "weight": "sem carga",
          "restTime": "45s",
          "notes": "Pausar por um segundo na posição estendida.",
          "order": 6
        },
        {
          "exerciseId": "0f49a078-0bfa-4276-a30c-7aaadd63fd54",
          "name": "Alongamento de flexor de quadril",
          "description": "Mobilidade para a parte anterior do quadril.",
          "purpose": "Reduzir rigidez na frente do quadril e favorecer postura e passada.",
          "instructions": "Em meio ajoelhado, levar o quadril suavemente à frente mantendo o tronco alinhado.",
          "safetyGuidance": "Usar apoio no joelho e não arquear a lombar.",
          "series": 2,
          "reps": "30 segundos por lado",
          "weight": "sem carga",
          "restTime": "20s",
          "notes": "Finalização em intensidade confortável.",
          "order": 7
        }
      ]
    },
    {
      "name": "Treino B - Cadeia posterior, equilíbrio e controle",
      "date": "2026-07-15",
      "description": "Sessão de fortalecimento da cadeia posterior, costas, glúteos e core, com estímulos de equilíbrio e condicionamento leve.",
      "objective": "Aumentar a estabilidade do corpo e fortalecer estruturas importantes para sustentar a corrida com boa técnica.",
      "focusAreas": "Posterior de coxa, glúteos, costas, core, equilíbrio e condicionamento de baixo impacto",
      "intensity": "moderada",
      "estimatedDurationMinutes": 50,
      "estimatedCaloriesMin": 190,
      "estimatedCaloriesMax": 270,
      "studentSummary": "Este treino complementa o primeiro, fortalecendo a parte posterior do corpo, as costas e o core. Também trabalha equilíbrio e controle, importantes para uma corrida mais estável.",
      "safetyNote": "A faixa de calorias é aproximada. Mantenha a execução controlada e ajuste carga, amplitude ou ritmo diante de dor, tontura ou falta de ar fora do esperado.",
      "notes": "Professor deve revisar a resposta ao Treino A antes de liberar esta sessão e confirmar que não surgiu dor ou desconforto.",
      "exercises": [
        {
          "exerciseId": "6c6c0e87-d7aa-4de9-9ae0-4abeb936dd46",
          "name": "Elevação de joelhos baixa",
          "description": "Elevação alternada de joelhos em baixa intensidade.",
          "purpose": "Aquecer com baixo impacto e preparar coordenação para a sessão.",
          "instructions": "Elevar os joelhos alternadamente em ritmo controlado.",
          "safetyGuidance": "Ajustar a altura dos joelhos conforme conforto e manter respiração regular.",
          "series": 1,
          "reps": "5 minutos",
          "weight": "sem carga",
          "restTime": "30s",
          "notes": "Manter intensidade leve.",
          "order": 0
        },
        {
          "exerciseId": "f6b34ce1-edd6-46bb-a949-1d4448ac5833",
          "name": "Mobilidade de quadril 90/90",
          "description": "Mobilidade de quadril em posição sentada.",
          "purpose": "Melhorar mobilidade dos quadris e preparar movimentos de força.",
          "instructions": "Sentar em 90/90 e alternar inclinações suaves dentro do conforto.",
          "safetyGuidance": "Não forçar dor articular nem compensar com a lombar.",
          "series": 2,
          "reps": "8 por lado",
          "weight": "sem carga",
          "restTime": "30s",
          "notes": "Movimento lento e controlado.",
          "order": 1
        },
        {
          "exerciseId": "2b981bff-cea6-4657-93bc-2f90f92a299a",
          "name": "Stiff com halteres",
          "description": "Dobradiça de quadril para posterior de coxa e glúteos.",
          "purpose": "Fortalecer a cadeia posterior, importante para propulsão e controle na corrida.",
          "instructions": "Com joelhos levemente flexionados, levar o quadril para trás mantendo a coluna neutra.",
          "safetyGuidance": "Usar carga moderada, manter a carga próxima ao corpo e interromper se houver dor lombar.",
          "series": 3,
          "reps": "10",
          "weight": "carga leve a moderada, definida pelo professor",
          "restTime": "75s",
          "notes": "Confirmar domínio da dobradiça antes de aumentar carga.",
          "order": 2
        },
        {
          "exerciseId": "04233bf3-5fd3-465b-bba8-b2b77dfdf7f3",
          "name": "Ponte de glúteo no solo",
          "description": "Ativação de glúteos e cadeia posterior no solo.",
          "purpose": "Fortalecer glúteos com baixo impacto e melhorar estabilidade pélvica.",
          "instructions": "Deitada, com joelhos flexionados, elevar o quadril contraindo os glúteos e retornar devagar.",
          "safetyGuidance": "Evitar compensar com a lombar e manter os pés firmes.",
          "series": 3,
          "reps": "12",
          "weight": "peso corporal ou carga leve",
          "restTime": "60s",
          "notes": "Pausar um segundo no topo sem hiperestender a lombar.",
          "order": 3
        },
        {
          "exerciseId": "cb4dc55e-e8d2-41be-a1ac-ecbb78055cf7",
          "name": "Remada unilateral apoiada",
          "description": "Remada com uma mão apoiada para maior estabilidade.",
          "purpose": "Fortalecer costas e postura, ajudando no controle do tronco durante a corrida.",
          "instructions": "Apoiar uma mão, puxar o peso com o outro braço mantendo o tronco firme.",
          "safetyGuidance": "Evitar girar o tronco ou elevar o ombro e usar carga controlável.",
          "series": 3,
          "reps": "10 por lado",
          "weight": "carga leve a moderada",
          "restTime": "60s",
          "notes": "Manter pescoço neutro.",
          "order": 4
        },
        {
          "exerciseId": "5d1ef3a1-78fc-406a-9e73-8d53f367ba6d",
          "name": "Equilíbrio unipodal",
          "description": "Estabilidade em apoio sobre um pé.",
          "purpose": "Melhorar estabilidade de tornozelo, quadril e core para a corrida.",
          "instructions": "Ficar em um pé mantendo postura e apoio próximo se necessário.",
          "safetyGuidance": "Executar perto de apoio firme e interromper em caso de dor ou perda de equilíbrio importante.",
          "series": 3,
          "reps": "30 segundos por lado",
          "weight": "sem carga",
          "restTime": "30s",
          "notes": "Progredir apenas se houver boa estabilidade.",
          "order": 5
        },
        {
          "exerciseId": "8603685a-aeb0-43c2-a8ca-6a77c21a8e3b",
          "name": "Dead bug",
          "description": "Exercício de core com controle lombar.",
          "purpose": "Aprimorar estabilidade do core e controle entre membros superiores e inferiores.",
          "instructions": "Deitada, mover braço e perna opostos mantendo a lombar controlada.",
          "safetyGuidance": "Executar devagar, respirar e reduzir amplitude se perder o controle lombar.",
          "series": 3,
          "reps": "8 por lado",
          "weight": "sem carga",
          "restTime": "45s",
          "notes": "Qualidade do movimento acima da velocidade.",
          "order": 6
        },
        {
          "exerciseId": "028f4f87-5e4d-471b-9a09-3353b1aac8f4",
          "name": "Polichinelo sem salto",
          "description": "Variação de polichinelo sem impacto.",
          "purpose": "Finalizar com condicionamento moderado e baixo impacto.",
          "instructions": "Abrir uma perna por vez lateralmente enquanto movimenta os braços.",
          "safetyGuidance": "Manter ritmo confortável, sem impacto, dor articular, tontura ou falta de ar importante.",
          "series": 3,
          "reps": "40 segundos",
          "weight": "sem carga",
          "restTime": "40s",
          "notes": "Usar como bloco final de condicionamento.",
          "order": 7
        },
        {
          "exerciseId": "436cfa0c-bb3e-47aa-a0f6-18983888e78e",
          "name": "Respiração diafragmática deitado",
          "description": "Exercício de respiração e recuperação.",
          "purpose": "Reduzir gradualmente a intensidade e favorecer recuperação.",
          "instructions": "Deitada, respirar expandindo abdômen e costelas e soltar o ar devagar.",
          "safetyGuidance": "Manter posição confortável, sem prender o ar ou tensionar o pescoço.",
          "series": 1,
          "reps": "3 minutos",
          "weight": "sem carga",
          "restTime": "sem intervalo",
          "notes": "Finalização da sessão.",
          "order": 8
        }
      ]
    }
  ]
}
